# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_ownner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='ownner',
            new_name='owner',
        ),
    ]
